library(shinytest2)

test_that("{shinytest2} recording: shinyapp", {
  app <- AppDriver$new("../..", variant = platform_variant(), name = "shinyapp",
      height = 1200, width = 1900)
  app$expect_screenshot()
  app$set_inputs(load_example = "Zug 2018")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(load_example = "Uri 2020")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(load_example = "Wikipedia EN")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(load_example = "Wikipedia DE")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(load_example = "Zug 2018")
  app$set_inputs(weight_votes = FALSE)
})
