library(shinytest2)

test_that("{shinytest2} recording: shinyapp", {
  app <- AppDriver$new("../..", variant = platform_variant(), name = "shinyapp",
      height = 1200, width = 1900)
  app$expect_screenshot()
  app$set_inputs(loadExample = "Zug 2018")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(loadExample = "Uri 2020")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(loadExample = "Wikipedia EN")
  app$wait_for_idle()
  app$expect_download("downloadResult", compare = testthat::compare_file_text)
  app$expect_download("downloadInput", compare = testthat::compare_file_text)
  app$expect_screenshot()
  app$set_inputs(loadExample = "Wikipedia DE")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(loadExample = "Zug 2018")
  app$wait_for_idle()
  app$expect_download("downloadResult", compare = testthat::compare_file_text)
  app$expect_download("downloadInput", compare = testthat::compare_file_text)
  app$expect_screenshot()
  app$set_inputs(weightVotes = FALSE)
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(n_cols = 2, n_rows = 2)
  app$click("run_update_matrix")
  app$wait_for_idle()
  app$expect_screenshot()
  app$set_inputs(seatsPerDistrict = FALSE)
  app$expect_screenshot()
  app$upload_file(uploadCSV = "../../../../tests/testthat/data/shiny-input-votes-seats.csv")
  app$wait_for_idle()
  app$expect_screenshot()
})
